# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/jenkinsxio/nexus
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: nexus
  type: ClusterIP
  externalPort: 80
  internalPort: 8081
  annotations:
    fabric8.io/expose: "true"
resources:
  # limits:
    # cpu: 100m
    # memory: 4Gi
  # requests:
    # cpu: 100m
    # memory: 2Gi
env:
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
securityContext:
  fsGroup: 2000

defaultAdminPassword: admin123
